global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'nginx'
#    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'nginx-exporter:9113' ]

  - job_name: 'mongodb'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets: [ 'mongo_exporter:9001' ]

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
      - targets:
        - http://localhost:80
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093